# Generated by Django 5.0.6 on 2024-08-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp3', '0002_vol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Vol',
        ),
    ]
